version: '3.4'

services:
  tasksmanagement:
    image: tasksmanagement
    build:
      context: .
      dockerfile: TasksManagement.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SQL_HOST=sqldb
      - SQL_PORT=1433
      - SQL_USER=sa
      - SQL_PASSWORD=SenhaSql12345
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=mongoUser
      - MONGO_PASSWORD=SenhaMongo12345
    ports:
      - "5000:8080"
    depends_on:
      - sqldb
      - mongodb
    networks:
      - backend

  sqldb:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=SenhaSql12345
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - backend

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoUser
      - MONGO_INITDB_ROOT_PASSWORD=SenhaMongo12345
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
